# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Memo
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'

  target 'MemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
